# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    error_controller: Frontend\Controller\ErrorController

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
      scoped_clients:
        blog_api_transport:
          base_uri: '%env(BLOG_HOST)%'

    rate_limiter:
      sensitive_api:
        policy: 'fixed_window'
        limit: 5
        interval: '1 minutes'
        cache_pool: cache.rate_limiter
