framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    cache:
      default_redis_provider: '%env(REDIS_URL)%'
      pools:
        cache.doctrine.result:
          adapter: cache.adapter.redis
          default_lifetime: PT10M
        cache.doctrine.query:
          adapter: cache.adapter.redis
          default_lifetime: PT1H
        cache.doctrine.metadata:
          adapter: cache.adapter.redis
          default_lifetime: P1D
