version: '3'
services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - appnet
    depends_on:
      - backend
  backend:
    build: ./
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - appnet
      - infranet
    depends_on:
      - db
      - cache
  db:
    image: sameersbn/postgresql
    environment:
      - DB_USER
      - DB_PASS
      - DB_NAME
    ports:
      - 5432
    networks:
      - infranet
  cache:
    image: redis
    networks:
      - infranet

networks:
  infranet:
  appnet:
