version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/app/public:ro
    ports:
      - "80:80"
    networks:
      - appnet
    depends_on:
      - backend
  backend:
    build: ./
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - appnet
      - infranet
    depends_on:
      - db
      - cache
  db:
    image: sameersbn/postgresql:12-20200524
    environment:
      - DB_USER
      - DB_PASS
      - DB_NAME
    ports:
      - '5432:5432'
    networks:
      - infranet
    volumes:
      - ./var/pgdata:/var/lib/postgresql
  cache:
    image: redis
    networks:
      - infranet

networks:
  infranet:
  appnet:
