version: '3.4'
services:
  frontend:
    build:
      context: ./frontend
      target: dev
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/docker/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ./frontend:/frontend
    ports:
      - "80:80"
    networks:
      - appnet
    depends_on:
      - backend
  backend:
    build:
      context: ./
      target: dev_container
    env_file:
      - .env
      - .env.dev
      - .env.local
    volumes:
      - ./:/app
      - .composer/:/var/www/.composer/
    networks:
      - appnet
      - infranet
    depends_on:
      - db
  db:
    image: sameersbn/postgresql:12-20200524
    environment:
      - DB_USER
      - DB_PASS
      - DB_NAME
    ports:
      - '5432:5432'
    networks:
      - infranet
    volumes:
      - db-storage:/var/lib/postgresql

networks:
  infranet:
  appnet:

volumes:
  db-storage:
