FROM nginx:1.21 as dev

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-venv libaugeas0 cron \
    && python3 -m venv /opt/certbot/ \
    && /opt/certbot/bin/pip install --upgrade pip \
    && /opt/certbot/bin/pip install certbot certbot-nginx \
    && ln -s /opt/certbot/bin/certbot /usr/bin/certbot

RUN echo "0 0 1 * * root certbot renew -q" | tee -a /etc/crontab

COPY ./.docker/nginx.conf /etc/nginx/templates/default.conf.template
