version: '3.4'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    environment:
      - BLOG_DOMAIN_NAME
      - SSLCERT_OWNER_EMAIL
    ports:
      - "80:80"
      - "443:443"
    networks:
      appnet:
        aliases:
          - blog.internal
    depends_on:
      - backend
    logging:
      driver: local
      options:
        max-size: "2m"
        max-file: "2"
    volumes:
      - ssl-cert:/etc/letsencrypt/
  backend:
    build:
      context: ./
      target: prod_container
      args:
        APP_ENV: ${APP_ENV}
    environment:
      - APP_ENV
      - APP_SECRET
      - MY_VERY_SECRET_TOKEN
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
      - DB_NAME
      - DB_VERSION
      - DB_DRIVER
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_ADMIN_CHAT_ID
      - ADMIN_NOTIFICATIONS_ENABLED
      - BLOG_HOST=http://blog.internal
      - BLOG_DOMAIN_NAME
    networks:
      - appnet
      - infranet
    depends_on:
      - db
      - cache
    logging:
      driver: local
      options:
        max-size: "1m"
        max-file: "2"
  db:
    image: sameersbn/postgresql:12-20200524
    environment:
      - DB_USER
      - DB_PASS
      - DB_NAME
    networks:
      - infranet
    volumes:
      - db-storage:/var/lib/postgresql
    logging:
      driver: local
      options:
        max-size: "2m"
        max-file: "2"
  cache:
    image: redis
    networks:
      - infranet
    logging:
      driver: local
      options:
        max-size: "1m"
        max-file: "2"

networks:
  infranet:
  appnet:

volumes:
  db-storage:
  ssl-cert:
