version: '3.4'
services:
  frontend:
    hostname: blog_server
    image: nginx:1.21
    environment:
      - BLOG_DOMAIN_NAME
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ./public:/app/public:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - appnet
    depends_on:
      - backend
  backend:
    build:
      context: ./
      target: prod_container
      args:
        APP_ENV: ${APP_ENV}
    environment:
      - APP_ENV
      - APP_SECRET
      - BLOG_HOST
      - MY_VERY_SECRET_TOKEN
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
      - DB_NAME
      - DB_VERSION
      - DB_DRIVER
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_ADMIN_CHAT_ID
      - ADMIN_NOTIFICATIONS_ENABLED
      - BLOG_HOST=https://blog_server
    networks:
      - appnet
      - infranet
    depends_on:
      - db
      - cache
  db:
    image: sameersbn/postgresql:12-20200524
    environment:
      - DB_USER
      - DB_PASS
      - DB_NAME
    ports:
      - '5432:5432'
    networks:
      - infranet
    volumes:
      - db-storage:/var/lib/postgresql
  cache:
    image: redis
    networks:
      - infranet

networks:
  infranet:
  appnet:

volumes:
  db-storage:
