version: '3'
services:
  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: ${REACT_APP_BACKEND_URL}
        BLOG_DOMAIN: ${BLOG_DOMAIN_NAME}
    environment:
      - BLOG_DOMAIN_NAME
      - REACT_APP_AUTHOR_NAME
      - REACT_APP_BACKEND_URL
      - REACT_APP_LINKEDIN_LINK
      - REACT_APP_GITHUB_LINK
    ports:
      - "80:80"
    networks:
      - appnet
    depends_on:
      - backend
  backend:
    build:
      context: ./
      args:
        APP_ENV: ${APP_ENV}
    environment:
      - APP_ENV
      - APP_SECRET
      - MY_VERY_SECRET_TOKEN
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
      - DB_NAME
      - DB_VERSION
      - DB_DRIVER
    networks:
      - appnet
      - infranet
    depends_on:
      - db
      - cache
  db:
    image: sameersbn/postgresql:12-20200524
    environment:
      - DB_USER
      - DB_PASS
      - DB_NAME
    ports:
      - '5432:5432'
    networks:
      - infranet
    volumes:
      - db-storage:/var/lib/postgresql
  cache:
    image: redis
    networks:
      - infranet

networks:
  infranet:
  appnet:

volumes:
  db-storage: