create_token:
  path: /auth/tokens
  methods: [ POST ]
  controller: App\Controller\IssueTokenController

index:
  path: /posts
  methods: [ GET ]
  controller: App\Controller\Post\ListController
create_post:
  path: /posts
  methods: [ POST ]
  controller: App\Controller\Post\CreateController
update_post:
  path: /posts/{slug}
  requirements:
    slug: '[a-zA-Z0-9_-]{10,}'
  methods: [ PATCH ]
  controller: App\Controller\Post\EditController
view_post:
  path: /posts/{slug}
  requirements:
    slug: '[a-zA-Z0-9_-]{10,}'
  methods: [ GET ]
  controller: App\Controller\Post\ViewController
add_comment:
  path: /posts/{slug}/comments
  requirements:
    slug: '[a-zA-Z0-9_-]{10,}'
  methods: [ POST ]
  controller: App\Controller\Comment\AddController
publish_post:
  path: /posts/{slug}/releases
  controller: App\Controller\Post\PublishController
  requirements:
    slug: '[a-zA-Z0-9_-]{10,}'
  methods: [ POST ]
reply_comment:
  path: /posts/{slug}/comments/{replyTo}
  requirements:
    slug: '[a-zA-Z0-9_-]{10,}'
    replyTo: '[a-z0-9]{8}(-[a-z0-9]{4}){3}-[a-z0-9]{12}'
  methods: [ POST ]
  controller: App\Controller\Comment\ReplyController
view_comments:
  path: /posts/{slug}/comments
  requirements:
    slug: '[a-zA-Z0-9_-]{10,}'
  methods: [ GET ]
  controller: App\Controller\Comment\ListController
