doctrine:
  orm:
    auto_generate_proxy_classes: false
    metadata_cache_driver:
      type: pool
      pool: cache.doctrine.metadata
    query_cache_driver:
      type: pool
      pool: cache.doctrine.query
    result_cache_driver:
      type: pool
      pool: cache.doctrine.result
