doctrine:
  orm:
    auto_generate_proxy_classes: false
    metadata_cache_driver:
      type: pool
      pool: cache.doctrine.metadata
    query_cache_driver:
      type: pool
      pool: cache.doctrine.query
    result_cache_driver:
      type: pool
      pool: cache.doctrine.result

framework:
  cache:
    pools:
      doctrine.result_cache_pool:
        adapter: cache.app
      doctrine.system_cache_pool:
        adapter: cache.system
