api_routes:
  prefix: /api
  name_prefix: 'api_'
  resource: 'routes/api.yaml'

index:
  path: /{page}
  requirements:
    page: '[1-9][0-9]*'
  defaults:
    page: 1
  methods: [ GET ]
  controller: Frontend\Controller\Post\ListController

blog:
  path: /blog/{page}
  requirements:
    page: '[1-9][0-9]*'
  defaults:
    page: 1
  methods: [ GET ]
  controller: Frontend\Controller\Post\ListController

blog_post:
  path: /blog/{slug}
  requirements:
    slug: '[a-zA-Z0-9_-]{10,}'
  methods: [ GET ]
  controller: Frontend\Controller\Post\ViewController
