
index:
    path: /api/posts
    methods: [GET]
    controller:  App\Controller\Post\ListController
create_post:
    path: /api/posts
    methods: [POST]
    controller:  App\Controller\Post\CreateController
view_post:
    path: /api/posts/{slug}
    methods: [GET]
    controller:  App\Controller\Post\ViewController
