services:
  _defaults:
    autowire: true
  blog.view.post:
    class: App\View\PostView
    tags: [{name: view, view: post.view}]

  blog.view.post_preview:
    class: App\View\PostView
    arguments:
      $isFull: false
    tags: [{name: view, view: post.preview}]

  # Application layer
  validation.violation_list:
    class: App\View\ConstraintViolationsView
    tags: [{name: view, view: constraints.violation}]

  response.system_message:
    class: App\Service\Response\View\SystemMessageView
    tags: [{name: view, view: response.system_message}]

  response.paginated_view:
    class: App\View\PaginatedView
    tags: [{name: view, view: response.paginated_collection}]

  blog.comment:
    class: App\View\CommentView
    tags: [{name: view, view: comment}]

  blog.post.comments:
    class: App\View\CommentsTreeView
    tags: [{name: view, view: post.comments_tree}]
