services:
  _defaults:
    autowire: true
  blog.view.post:
    class: App\View\PostView
    tags: [{name: view, view: post.view}]

  blog.view.post_preview:
    class: App\View\PostView
    arguments:
      $isFull: false
    tags: [{name: view, view: post.preview}]

  blog.view.post_list:
    class: Temirkhan\View\CollectionView
    arguments:
      $elementViewName: 'post.preview'
    tags: [{name: view, view: post.list}]

  # Application layer
  validation.violation_list:
    class: App\View\ConstraintViolationsView
    tags: [{name: view, view: constraints.violation}]

  response.system_message:
    class: App\Service\Response\View\SystemMessageView
    tags: [{name: view, view: response.system_message}]
