index:
  path: /{page}
  requirements:
    page: '[1-9][0-9]*'
  defaults:
    page: 1
  methods: [ GET ]
  controller: Frontend\Controller\Post\ListController

blog:
  path: /blog/{page}
  requirements:
    page: '[1-9][0-9]*'
  defaults:
    page: 1
  methods: [ GET ]
  controller: Frontend\Controller\Post\ListController

blog_post:
  path: /blog/{slug}
  requirements:
    slug: '[a-zA-Z0-9_-]{10,}'
  methods: [ GET ]
  controller: Frontend\Controller\Post\ViewController

login:
  path: /login
  methods: [GET, POST]
  controller: Frontend\Controller\Admin\LoginController

edit_post:
  path: /admin/post
  methods: [GET, POST]
  controller: Frontend\Controller\Admin\PostEditorController
