index:
  path: /
  methods: [ GET ]
  controller: Frontend\Controller\Post\ListController

blog_posts_by_tag:
  path: /blog/tag/{tag}/{page}
  stateless: true
  requirements:
    tag: '[a-zA-Z0-9]+'
    page: '[1-9][0-9]*'
  defaults:
    page: 1
  methods: [ GET ]
  controller: Frontend\Controller\Post\ListController

blog:
  path: /blog/{page}
  stateless: true
  requirements:
    page: '[1-9][0-9]*'
  defaults:
    page: 1
  methods: [ GET ]
  controller: Frontend\Controller\Post\ListController

blog_post:
  path: /blog/{id}_{slug}
  stateless: true
  requirements:
    id: '[1-9][0-9]*'
    slug: '[a-zA-Z0-9_-]{10,}'
  methods: [ GET ]
  controller: Frontend\Controller\Post\ViewController

blog_post_backward_compatibility:
  path: /blog/{slug}
  stateless: true
  requirements:
    slug: '[a-zA-Z0-9_-]{10,}'
  methods: [ GET ]
  controller: Frontend\Controller\Post\ViewController

blog_post_comments_action:
  path: /blog/{id}_{slug}/comments
  requirements:
    id: '[1-9][0-9]*'
    slug: '[a-zA-Z0-9_-]{10,}'
  methods: [ POST ]
  controller: Frontend\Controller\Post\CommentController

login:
  path: /admin/login
  methods: [GET, POST]
  controller: Frontend\Controller\Admin\LoginController

# currently /admin/post is resolved as 0(page for new post creation)
admin_edit_post:
  path: /admin/post/{id}
  requirements:
    id: '[1-9][0-9]*'
  defaults:
    id: 0
  methods: [GET, POST]
  controller: Frontend\Controller\Admin\PostEditorController

admin_list_posts:
  path: /admin/posts/{page}
  methods: [GET, POST]
  requirements:
    page: '[1-9][0-9]*'
  defaults:
    page: 1
  controller: Frontend\Controller\Admin\PostListController

static_pages:
  path: /{name}
  stateless: true
  methods: [GET]
  controller: Frontend\Controller\MarkdownPageController
  requirements:
    name: about

error.not_found:
  path: /404
  stateless: true
  methods: [GET]
  controller: Frontend\Controller\ErrorController::notFound

sitemap:
  path: /sitemap.xml
  stateless: true
  methods: [GET]
  controller: Frontend\Controller\SitemapController
