services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true
  Frontend\:
    resource: '../{API,Service}'
    exclude: '../Resource/'


  Frontend\Controller\:
    resource: '../Controller'
    tags: ['controller.service_arguments']

  Twig\Loader\FilesystemLoader:
    arguments:
      - ['%kernel.project_dir%/frontend/Resource/View/']
  # TODO cache, strict and etc
  Twig\Environment:
    arguments:
      - '@Twig\Loader\FilesystemLoader'
