services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true
  Frontend\:
    resource: '../{API,Service,Event}'
    exclude: '../Resource/'

  Frontend\Controller\:
    resource: '../Controller'
    tags: ['controller.service_arguments']

  Frontend\API\Client:
    arguments:
      - '@blog_api_transport'
