name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: '7.4'
      - run: composer install --no-interaction
      - run: ./vendor/bin/phpcs
      - run: ./vendor/bin/phpstan
      - run: ./vendor/bin/phpunit
