name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.4
          php_extensions: redis
      - run: ./vendor/bin/phpcs
      - run: ./vendor/bin/phpunit
