name: CI

on: [ push ]

jobs:
  backend_quality_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: '8.3'
      - name: install dependencies
        run: composer install --no-interaction
      - name: codestyle
        run: ./vendor/bin/phpcs
      - name: static analyze
        run: ./vendor/bin/phpstan
      - name: tests
        run: ./vendor/bin/phpunit
      - name: architecture layers analyze
        run: ./vendor/bin/deptrac analyze
