name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [7.4]

    steps:
      - uses: actions/checkout@v2
      - run: composer install --no-interaction --dev
      - run: ./vendor/bin/phpcs
      - run: ./vendor/bin/phpunit
