name: CI

on: [push, pull_request]

jobs:
  backend_quality_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - name: install dependencies
        run: composer install --no-interaction
      - name: codestyle
        run: ./vendor/bin/phpcs
      - name: static analysis
        run: ./vendor/bin/phpstan
      - name: tests
        run: ./vendor/bin/phpunit
      - name: architecture layers analyze
        run: ./vendor/bin/deptrac analyze
