App\Entity\Comment:
  type: entity
  table: comments
  id:
    guid:
      type: string
      length: 36
      generator:
        strategy: NONE
  fields:
    comment:
      type: text
      length: 400
    repliedToCommentGuid:
      type: string
      length: 36
      nullable: true
  manyToOne:
    post:
      targetEntity: App\Entity\Post
      inversedBy: comments
      joinColumn:
        name: post_slug
        referencedColumnName: slug
        cascade: [remove]
        onDelete: CASCADE
