App\Entity\Comment:
  type: entity
  table: comments
  readOnly: true
  indexes:
    created_at_idx:
      columns: [created_at]
  id:
    guid:
      type: string
      length: 36
      generator:
        strategy: NONE
  fields:
    comment:
      type: text
      length: 400
    repliedToCommentGuid:
      type: string
      length: 36
      nullable: true
    createdAt:
      type: datetime_immutable
      options:
        default: CURRENT_TIMESTAMP
  manyToOne:
    post:
      targetEntity: App\Entity\Post
      inversedBy: comments
      joinColumn:
        name: post_id
        referencedColumnName: id
        nullable: false
