App\Entity\Post:
  type: entity
  table: posts
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
      options:
        unsigned: true
  fields:
    state:
      type: integer
      options:
        unsigned: true
        default: 0
    slug:
      type: string
      length: 255
      unique: true
    title:
      type: string
      length: 200
    preview:
      type: text
    content:
      type: text
    createdAt:
      type: datetime_immutable
      options:
        default: CURRENT_TIMESTAMP
    publishedAt:
      type: datetime_immutable
      nullable: true
    updatedAt:
      type: datetime_immutable
      nullable: true
  oneToMany:
    comments:
      targetEntity: App\Entity\Comment
      mappedBy: post
    tags:
      targetEntity: App\Entity\Tag
      mappedBy: post

