App\Entity\Post:
  type: entity
  table: posts
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
      options:
        unsigned: true
  fields:
    slug:
      type: string
      length: 255
      unique: true
    title:
      type: string
      length: 200
    preview:
      type: text
    content:
      type: text
    publishedAt:
      type: datetime_immutable
  manyToMany:
    tags:
      targetEntity: App\Entity\Tag
      joinTable:
        name: posts_tags
        joinColumns:
          post_id:
            referencedColumnName: id
        inverseJoinColumns:
          tag_id:
            referencedColumnName: name
      cascade:
        - persist
  oneToMany:
    comments:
      targetEntity: App\Entity\Comment
      mappedBy: post
