App\Entity\Tag:
  type: entity
  table: tags
  readOnly: true
  id:
    id:
      type: integer
      generator:
        strategy: IDENTITY
      options:
        unsigned: true
  fields:
    name:
      type: string
      length: 50
  manyToOne:
    post:
      targetEntity: App\Entity\Post
      inversedBy: tags
      joinColumn:
        name: post_id
        referencedColumnName: id
