App\Entity\Tag:
  type: entity
  table: tags
  readOnly: true
  id:
    name:
      type: string
      length: 50
      generator:
        strategy: NONE
  manyToOne:
    post:
      targetEntity: App\Entity\Post
      inversedBy: tags
      joinColumn:
        name: post_id
        referencedColumnName: id
        nullable: false
        cascade: [remove]
        onDelete: CASCADE
